name: 'Deploy to Ploi'

#on:
#  push:
#    branches:
#      - master
on: workflow_dispatch

jobs:
  ploi-deploy:
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy conductor-01
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.PLOI_DEPLOY_TRIGGER_URL }}
